#!/usr/bin/env bash
#
# Renders the nginx route from acl.json: one location per principal, each
# injecting that principal's API key.
#
# The route and the ACL are two views of the same list, so generating one from
# the other is what stops them drifting. Adding a principal becomes a single
# edit to acl.json followed by a re-render.
#
#   ./render-route.sh > todoist.conf     # then install and reload nginx
#   ACL=/path/to/acl.json ./render-route.sh
#
# The output contains real API keys. Keep it out of version control and mode 600.

set -euo pipefail

ACL=${ACL:-$(dirname "$0")/acl.json}
UPSTREAM=${UPSTREAM:-http://127.0.0.1:8008/}
PREFIX=${PREFIX:-/api/todoist}
AGENT_HEADER=${AGENT_HEADER:-}

[ -f "$ACL" ] || { echo "render-route: $ACL not found" >&2; exit 1; }

ACL="$ACL" UPSTREAM="$UPSTREAM" PREFIX="$PREFIX" AGENT_HEADER="$AGENT_HEADER" python3 <<'PY'
import json, os, re, sys

acl = json.load(open(os.environ["ACL"]))
upstream = os.environ["UPSTREAM"]
prefix = os.environ["PREFIX"].rstrip("/")
agent_header = os.environ.get("AGENT_HEADER", "")

print(f"""# GENERATED by render-route.sh from acl.json — do not edit by hand.
#
# One location per principal. nginx stamps the key, so the consumer holds no
# credential at all and cannot promote itself by sending a different one: the
# proof of identity is the path the request arrived on.
#
# Caveat worth keeping in view: any process that can reach this listener can
# call every location on it. Two principals are only meaningfully separated
# here if the narrower one cannot open sockets — so give the broader scope to
# the consumer that has shell access, never the other way round.
#
# Regenerate after editing acl.json:
#   ./render-route.sh > todoist.conf && install -m 600 -o root -g root todoist.conf <dest>
#   nginx -t && systemctl reload nginx""")

for name, principal in acl.get("principals", {}).items():
    if not re.fullmatch(r"[a-z0-9][a-z0-9_-]*", name):
        sys.exit(f"render-route: principal name {name!r} is not safe for a URL path")
    scope = principal.get("projects")
    scope = "all mapped projects" if scope == "*" else ", ".join(scope)
    print(f"""
# {name} — role {principal['role']}; projects: {scope}
location {prefix}/{name}/ {{
    proxy_pass {upstream};
    proxy_http_version 1.1;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # Replaces any X-Api-Key the caller sent.
    proxy_set_header X-Api-Key {principal['apiKey']};""")
    if agent_header:
        print(f"    proxy_set_header X-Openclaw-Agent {agent_header};")
    print("""
    # Required for the MCP SSE keep-alive on GET /mcp.
    proxy_set_header Connection '';
    proxy_buffering off;

    client_max_body_size 1m;
    proxy_read_timeout 60s;
    proxy_connect_timeout 10s;
}""")
PY
